### ISSUE TITLE
charmworld on Launchpad referenced in page footer

### ISSUE THREAD

**Issue by stub42** [canonical/jujucharms.com#21]
The charmworld project on Launchpad is referenced in the page footer. Apparently this is old, and in addition is still configured to accept bugs on Launchpad rather than pointing to this external bug tracker.

**Comment by mitechie** [comment]
@stub42 can you point to the url and where you saw a reference to charmworld? 

The footer bug link is pointing to a web team project at the moment. (https://bugs.launchpad.net/juju-website) We've got an upcoming release (hopefully today) that will change that link to this issue tracker. 

Closing as fix committed. That brings up we need a better way to track fix committed vs fix released with these github issues.

**Comment by stub42** [comment]
https://manage.jujucharms.com/charms/precise/block-storage-broker has the link near the bottom next to 'Learn more about'.

This would be the old site, which unfortunately still appears very much alive and has more google juice than the new site.
